

apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: jenkins-k8s
spec:
  selector:
    matchLabels:
      app: jenkins-k8s
  replicas: 2 
  template:
    metadata:
      labels:
        app: jenkins-k8s
    spec:
      containers:
        - name: jenkins-k8s
          image: manjunathsvec/manjunathrepo:jenkins-k8s_13 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 

---

apiVersion: v1
kind: Service 
metadata:
  name: jenkins-k8s
spec:
  selector:
    app: jenkins-k8s
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort # type of the service.
